# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151024185721 on 2015-11-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20151119_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='txt',
            field=models.TextField(default=b'A'),
        ),
    ]
